# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    # Temporarily disabled - too many pre-existing unused code
    # - unused
    - gofmt
    - goimports
    - gosec
    # Temporarily disabled - too many constant suggestions
    # - goconst
    - revive
    - unconvert
    # Temporarily disabled - missing context in http calls
    # - noctx
    - bodyclose

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict for existing code
      - shadow          # Allow variable shadowing

  gocyclo:
    min-complexity: 15

  revive:
    confidence: 0.8
    rules:
      - name: exported
        severity: warning
      - name: error-return
        severity: warning
      - name: error-naming
        severity: warning
      - name: if-return
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning
      - name: range
        severity: warning
      - name: time-naming
        severity: warning

  gosec:
    excludes:
      - G104 # Audit errors not checked
    confidence: medium

  misspell:
    locale: US

  goimports:
    local-prefixes: github.com/gorax/gorax

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - goconst

    # Exclude known issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude deprecated strings.Title warning (fix planned for later)
    - text: "SA1019: strings.Title"
      linters:
        - staticcheck

    # Exclude unparam warnings (too noisy for existing code)
    - path: \.go$
      linters:
        - unparam

    # Exclude prealloc warnings (optimization not critical)
    - path: \.go$
      linters:
        - prealloc

    # Exclude revive stutter warnings
    - text: "stutters"
      linters:
        - revive

    # Exclude goconst warnings (too strict for this codebase)
    - path: \.go$
      linters:
        - goconst

    # Exclude integer overflow warnings (handled appropriately)
    - text: "G115"
      linters:
        - gosec

    # Exclude weak random warnings (not used for security)
    - text: "G404"
      linters:
        - gosec

    # Exclude TLS min version warnings (internal services)
    - text: "G402"
      linters:
        - gosec

    # Exclude context key type warnings (pre-existing code)
    - text: "SA1029"
      linters:
        - staticcheck

    # Exclude deprecated API warnings (planned for fix)
    - text: "SA1019"
      linters:
        - staticcheck

    # Exclude S1009 nil check warnings
    - text: "S1009"
      linters:
        - gosimple

    # Exclude S1016 struct conversion warnings
    - text: "S1016"
      linters:
        - gosimple

    # Exclude var-naming warnings (existing code style)
    - text: "var-naming"
      linters:
        - revive

    # Exclude if-return redundant check warnings
    - text: "if-return"
      linters:
        - revive

    # Exclude S1031 unnecessary nil check warnings
    - text: "S1031"
      linters:
        - gosimple

    # Exclude S1011 replace loop warnings
    - text: "S1011"
      linters:
        - gosimple

    # Exclude S1039 unnecessary fmt.Sprintf warnings
    - text: "S1039"
      linters:
        - gosimple

    # Exclude unusedwrite warnings (struct initializations)
    - text: "unusedwrite"
      linters:
        - govet

    # Exclude unnecessary conversion warnings
    - path: \.go$
      linters:
        - unconvert

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  print-issued-lines: true
  print-linter-name: true
